### ISSUE TITLE
Era Cluster ID README Clarification

### ISSUE THREAD

**Issue by nutanix-japan** [nutanix-cloud-native/ndb-operator#34]
Hello the manifest for creating a Postgres DB needs to specify Era cluster ID rather than just cluster ID.

For example it could be: 

```yaml
spec:
  # NDB server specific details
  ndb:
    # Cluster id of the cluster where the Database has to be provisioned
    # Can be fetched from the GET /clusters endpoint ``add: from Era CLI/API``
    clusterId: "EraCluster Id" 
```

    Instead of << clusterId: "Nutanix Cluster Id" >>

Here is the API response fro GET clusters from Era API
```json
{
    "id": "af193c0a-b8f5-47e1-a416-d50e0715b5fd",
    "name": "EraCluster",
    "uniqueName": "ERACLUSTER",
    "ipAddresses": [
      "10.38.x.x"
    ],
```
