### ISSUE TITLE
Redesign CRD for NDB to meet Cloud Native Security standards

### ISSUE THREAD

**Issue by abdennour** [nutanix-cloud-native/ndb-operator#40]
**Is your feature request related to a problem? Please describe.**
Yes it's a problem to expose the prism secret/creds to developers & delivery teams in general.
I mean this part:
```yaml
spec:
  # NDB server specific details
  ndb:
    # Cluster id of the cluster where the Database has to be provisioned
    # Can be fetched from the GET /clusters endpoint
    clusterId: "Nutanix Cluster Id" 
    # Credentials secret name for NDB installation
    # data: username, password, 
    # stringData: ca_certificate
    credentialSecret: your-ndb-secret
    # The NDB Server
    server: https://[NDB IP]:8443/era/v0.9
    # Set to true to skip SSL verification, default: false.
    skipCertificateVerification: false
```

**Describe the solution you'd like**
Remove `k explain database.spec.ndb` from the CRD Database & shift it to the controller runtime configuration.
And if it requires to override something at CRD Database, it can be anything but not credentials.

**Describe alternatives you've considered**
For the time being, we can contribute here as you are already a partner of our organization.
If we will find it's hard to contribute with you, or it took longtime to release whatever we contributed, that time, we will go to wrap your CRD with a helm-based operator by defaulting this credential value (i.e. watches.yaml)

**Additional context**
MENA regions , go-based operator
