### ISSUE TITLE
Please Start  S3 operator ASAP

### ISSUE THREAD

**Issue by abdennour** [nutanix-cloud-native/ndb-operator#41]
**Is your feature request related to a problem? Please describe.**
Since this is the go-based operator by Nutanix, i dropped this feature request here, because i cannot see any place more relevant than this place. So please accept it here , or move it & notify me.

**Describe the solution you'd like**

```yaml
apiVersion: s3.nutanix.com/v1alpha1
kind: Bucket
spec:
  events:
      kafka:
         topic: xyx
```
+ an admission controller to coordinate with the resourceQuota of each namespace & compare it with the requested storage. I know that S3 is unlimited, but please consider a soft quota ( software-defined)

**Describe alternatives you've considered**
We gonna build our own cloud operator with a multi-cloud architecture. So it comes from you it will be better, as we are partners.

**Additional context**
N/A
